# Generated by Django 4.2.5 on 2024-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
