# Generated by Django 4.2.5 on 2024-02-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Doctor", "0003_doctor_hospital"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="is_confirmed", new_name="status",
        ),
    ]
